#!/bin/bash

if [ ! -f ./venv/Scripts/python ] && [ ! -f ./venv/bin/python ]; then
    echo "setting up environment..."
    ./setup
fi

if [ -f ./venv/Scripts/python ]; then
    ./venv/Scripts/python ./main.py
else
    ./venv/bin/python ./main.py
fi